import { createElement } from "react";
import {
  Activity,
  BadgeCheck,
  Bell,
  BookMarked,
  BookOpen,
  Boxes,
  Brain,
  CircleDot,
  ClipboardCheck,
  Code,
  Drama,
  FlaskConical,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequestArrow,
  Hammer,
  Infinity as InfinityIcon,
  Keyboard,
  Layers,
  Lightbulb,
  Link2,
  ListOrdered,
  Map as MapIcon,
  Milestone,
  Package,
  PackageCheck,
  Repeat,
  Rocket,
  Server,
  Settings,
  ShieldCheck,
  Target,
  Timer,
  Trophy,
  Upload,
  User,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "badge-check": BadgeCheck,
  bell: Bell,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  boxes: Boxes,
  brain: Brain,
  "clipboard-check": ClipboardCheck,
  code: Code,
  drama: Drama,
  flask: FlaskConical,
  "git-commit": GitCommitHorizontal,
  "git-merge": GitMerge,
  "git-pull-request-arrow": GitPullRequestArrow,
  hammer: Hammer,
  infinity: InfinityIcon,
  keyboard: Keyboard,
  layers: Layers,
  lightbulb: Lightbulb,
  "link-2": Link2,
  "list-ordered": ListOrdered,
  map: MapIcon,
  milestone: Milestone,
  package: Package,
  "package-check": PackageCheck,
  repeat: Repeat,
  rocket: Rocket,
  server: Server,
  settings: Settings,
  "shield-check": ShieldCheck,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  upload: Upload,
  user: User,
  users: Users,
  workflow: Workflow,
  zap: Zap,
};

export function Icon({
  name,
  className,
  strokeWidth,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  return createElement(ICONS[name] ?? CircleDot, {
    className,
    strokeWidth,
    "aria-hidden": true,
  });
}
